<a href="https://colab.research.google.com/github/kedarvartak/Numpy/blob/main/numpy-basics-01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

# Array in Numpy
Arrays in numpy are have some restrictions -

* All elements of the array must be of the **same type of data**

* Once created, the **total size of the array can’t change**

* The shape must be “rectangular”, not “jagged”; e.g., **each row of a two-dimensional array must have the same number of columns**

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

In [ ]:
a = np.array([1, 22, 3, 4, 5, 6])
a

array([ 1, 22,  3,  4,  5,  6])

Elements of an array can be accessed in various ways -


*   Accessing a single element from array - This is done the same way as we do in a list. **arrayname[index]**
For example, for above array we would access the array element 1 as - **a[0]**
which would retrieve us 1.

In [ ]:
a[1]

np.int64(22)

Arrays are mutable, just like lists. Which means, when we change something in an array, the original existing array is modified and python does not create a new object for each new change

In [ ]:
a[:3]

array([ 1, 22,  3])

# Slicing in Python
- Slicing a list in a python is like viewing it in parts, you only view the part you need, imagine that you just want to view the first 3 numbers out of the entire array, in that case we use - **a[:3]**
 Syntax - **sequence[start:stop:step]**
- start: Index to begin the slice (inclusive)

- stop: Index to end the slice (exclusive)

- step: (Optional) How many steps to move forward

BUT - Slicing an array in numpy is different, see when you execute **a[:3]** on a list python copies the first 3 elements in another object and displays that, **but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view**

In [ ]:
b = a[3:]
b
b[0] = 40
a

array([ 1, 22,  3, 40,  5,  6])